# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: terminal 1
    before: echo 'before script'
    init: echo 'init script' # runs during prebuild
    command: echo 'start script'
  - name: terminal 2
    init: echo 'terminal 2'
    command: pip3 install mysql-connector-python

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
